# Generated by Django 4.2.2 on 2023-11-10 13:11

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('Family', 'Family'), ('extended', 'extended')], max_length=225)),
                ('currency', models.CharField(choices=[('$', '$'), ('₦', '₦'), ('R', 'R'), ('₹', '₹'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₽', '₽')], max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas, The'), ('BHR', 'Bahrain'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BTN', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BWA', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('KHM', 'Cambodia'), ('CMR', 'Cameroon'), ('CAN', 'Canada'), ('CPV', 'Cape Verde'), ('CAF', 'Central African Republic'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('COD', 'Congo, Democratic Republic of the'), ('COG', 'Congo, Republic of the'), ('CRI', 'Costa Rica'), ('CIV', 'Côte d Ivoire'), ('HRV', 'Croatia'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('CYP', 'Cyprus'), ('CZE', 'Czechia'), ('DNK', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('TLS', 'East Timor'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('SLV', 'El Salvador'), ('GNQ', 'Equatorial Guinea'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('SWZ', 'Eswatini'), ('ETH', 'Ethiopia'), ('FJI', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GMB', 'Gambia, The'), ('GEO', 'Georgia'), ('DEU', 'Germany'), ('GHA', 'Ghana'), ('GRC', 'Greece'), ('GRD', 'Grenada'), ('GTM', 'Guatemala'), ('GIN', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('PRK', 'Korea, North'), ('KOR', 'Korea, South'), ('KWT', 'Kuwait'), ('KGZ', 'Kyrgyzstan'), ('LAO', 'Laos'), ('LVA', 'Latvia'), ('LBN', 'Lebanon'), ('LSO', 'Lesotho'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MWI', 'Malawi'), ('MYS', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MHL', 'Marshall Islands'), ('MRT', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MAR', 'Morocco'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NOR', 'Norway'), ('OMN', 'Oman'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PHL', 'Philippines'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('VCT', 'Saint Vincent and the Grenadines'), ('WSM', 'Samoa'), ('SMR', 'San Marino'), ('STP', 'Sao Tome and Principe'), ('SAU', 'Saudi Arabia'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SGP', 'Singapore'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SLB', 'Solomon Islands'), ('SOM', 'Somalia'), ('ZAF', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('SYR', 'Syria'), ('TWN', 'Taiwan'), ('TJK', 'Tajikistan'), ('TZA', 'Tanzania'), ('THA', 'Thailand'), ('TGO', 'Togo'), ('TON', 'Tonga'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('ARE', 'United Arab Emirates'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe')], max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('house_address', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('image_5', models.ImageField(upload_to='')),
                ('slug', models.SlugField(default=book.models.generate_random_number_for_slug, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=225)),
                ('town', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=250)),
                ('id_type', models.CharField(choices=[('National Identification Number', 'National Identification Number'), ('Passport', 'Passport'), ('Driver License', 'Driver License')], max_length=225)),
                ('id_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(choices=[('Employed', 'employed'), ('Un-Employed', 'Un-Employed')], max_length=200)),
                ('number_of_day', models.IntegerField()),
                ('visited_for', models.CharField(choices=[('Vocation', 'Vocation'), ('Holiday', 'Holiday')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=book.models.generate_random_number, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('$', '$'), ('₦', '₦'), ('R', 'R'), ('₹', '₹'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₽', '₽')], max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas, The'), ('BHR', 'Bahrain'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BTN', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BWA', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('KHM', 'Cambodia'), ('CMR', 'Cameroon'), ('CAN', 'Canada'), ('CPV', 'Cape Verde'), ('CAF', 'Central African Republic'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('COD', 'Congo, Democratic Republic of the'), ('COG', 'Congo, Republic of the'), ('CRI', 'Costa Rica'), ('CIV', 'Côte d Ivoire'), ('HRV', 'Croatia'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('CYP', 'Cyprus'), ('CZE', 'Czechia'), ('DNK', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('TLS', 'East Timor'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('SLV', 'El Salvador'), ('GNQ', 'Equatorial Guinea'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('SWZ', 'Eswatini'), ('ETH', 'Ethiopia'), ('FJI', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GMB', 'Gambia, The'), ('GEO', 'Georgia'), ('DEU', 'Germany'), ('GHA', 'Ghana'), ('GRC', 'Greece'), ('GRD', 'Grenada'), ('GTM', 'Guatemala'), ('GIN', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('PRK', 'Korea, North'), ('KOR', 'Korea, South'), ('KWT', 'Kuwait'), ('KGZ', 'Kyrgyzstan'), ('LAO', 'Laos'), ('LVA', 'Latvia'), ('LBN', 'Lebanon'), ('LSO', 'Lesotho'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MWI', 'Malawi'), ('MYS', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MHL', 'Marshall Islands'), ('MRT', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MAR', 'Morocco'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NOR', 'Norway'), ('OMN', 'Oman'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PHL', 'Philippines'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('VCT', 'Saint Vincent and the Grenadines'), ('WSM', 'Samoa'), ('SMR', 'San Marino'), ('STP', 'Sao Tome and Principe'), ('SAU', 'Saudi Arabia'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SGP', 'Singapore'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SLB', 'Solomon Islands'), ('SOM', 'Somalia'), ('ZAF', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('SYR', 'Syria'), ('TWN', 'Taiwan'), ('TJK', 'Tajikistan'), ('TZA', 'Tanzania'), ('THA', 'Thailand'), ('TGO', 'Togo'), ('TON', 'Tonga'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('ARE', 'United Arab Emirates'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe')], max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('town', models.CharField(max_length=225)),
                ('land_address', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=15)),
                ('land_type', models.CharField(choices=[('Lake', 'Lake'), ('Hills', 'Hills')], max_length=100)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(default=book.models.generate_random_number_for_slug, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Quad', 'Quad')], max_length=225)),
                ('currency', models.CharField(choices=[('$', '$'), ('₦', '₦'), ('R', 'R'), ('₹', '₹'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₽', '₽')], max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas, The'), ('BHR', 'Bahrain'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BTN', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BWA', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('KHM', 'Cambodia'), ('CMR', 'Cameroon'), ('CAN', 'Canada'), ('CPV', 'Cape Verde'), ('CAF', 'Central African Republic'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('COD', 'Congo, Democratic Republic of the'), ('COG', 'Congo, Republic of the'), ('CRI', 'Costa Rica'), ('CIV', 'Côte d Ivoire'), ('HRV', 'Croatia'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('CYP', 'Cyprus'), ('CZE', 'Czechia'), ('DNK', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('TLS', 'East Timor'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('SLV', 'El Salvador'), ('GNQ', 'Equatorial Guinea'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('SWZ', 'Eswatini'), ('ETH', 'Ethiopia'), ('FJI', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GMB', 'Gambia, The'), ('GEO', 'Georgia'), ('DEU', 'Germany'), ('GHA', 'Ghana'), ('GRC', 'Greece'), ('GRD', 'Grenada'), ('GTM', 'Guatemala'), ('GIN', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('PRK', 'Korea, North'), ('KOR', 'Korea, South'), ('KWT', 'Kuwait'), ('KGZ', 'Kyrgyzstan'), ('LAO', 'Laos'), ('LVA', 'Latvia'), ('LBN', 'Lebanon'), ('LSO', 'Lesotho'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MWI', 'Malawi'), ('MYS', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MHL', 'Marshall Islands'), ('MRT', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MAR', 'Morocco'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NOR', 'Norway'), ('OMN', 'Oman'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PHL', 'Philippines'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('VCT', 'Saint Vincent and the Grenadines'), ('WSM', 'Samoa'), ('SMR', 'San Marino'), ('STP', 'Sao Tome and Principe'), ('SAU', 'Saudi Arabia'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SGP', 'Singapore'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SLB', 'Solomon Islands'), ('SOM', 'Somalia'), ('ZAF', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('SYR', 'Syria'), ('TWN', 'Taiwan'), ('TJK', 'Tajikistan'), ('TZA', 'Tanzania'), ('THA', 'Thailand'), ('TGO', 'Togo'), ('TON', 'Tonga'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('ARE', 'United Arab Emirates'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe')], max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('town', models.CharField(max_length=225)),
                ('room_address', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=15)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('image_5', models.ImageField(upload_to='')),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(default=book.models.generate_random_number, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('link', models.URLField()),
                ('room_id_number', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Quad', 'Quad')], max_length=225)),
                ('price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('currency', models.CharField(choices=[('$', '$'), ('₦', '₦'), ('R', 'R'), ('₹', '₹'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₽', '₽')], max_length=255)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas, The'), ('BHR', 'Bahrain'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BTN', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BWA', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('KHM', 'Cambodia'), ('CMR', 'Cameroon'), ('CAN', 'Canada'), ('CPV', 'Cape Verde'), ('CAF', 'Central African Republic'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('COD', 'Congo, Democratic Republic of the'), ('COG', 'Congo, Republic of the'), ('CRI', 'Costa Rica'), ('CIV', 'Côte d Ivoire'), ('HRV', 'Croatia'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('CYP', 'Cyprus'), ('CZE', 'Czechia'), ('DNK', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('TLS', 'East Timor'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('SLV', 'El Salvador'), ('GNQ', 'Equatorial Guinea'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('SWZ', 'Eswatini'), ('ETH', 'Ethiopia'), ('FJI', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GMB', 'Gambia, The'), ('GEO', 'Georgia'), ('DEU', 'Germany'), ('GHA', 'Ghana'), ('GRC', 'Greece'), ('GRD', 'Grenada'), ('GTM', 'Guatemala'), ('GIN', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('PRK', 'Korea, North'), ('KOR', 'Korea, South'), ('KWT', 'Kuwait'), ('KGZ', 'Kyrgyzstan'), ('LAO', 'Laos'), ('LVA', 'Latvia'), ('LBN', 'Lebanon'), ('LSO', 'Lesotho'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MWI', 'Malawi'), ('MYS', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MHL', 'Marshall Islands'), ('MRT', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MAR', 'Morocco'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NOR', 'Norway'), ('OMN', 'Oman'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PHL', 'Philippines'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('VCT', 'Saint Vincent and the Grenadines'), ('WSM', 'Samoa'), ('SMR', 'San Marino'), ('STP', 'Sao Tome and Principe'), ('SAU', 'Saudi Arabia'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SGP', 'Singapore'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SLB', 'Solomon Islands'), ('SOM', 'Somalia'), ('ZAF', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('SYR', 'Syria'), ('TWN', 'Taiwan'), ('TJK', 'Tajikistan'), ('TZA', 'Tanzania'), ('THA', 'Thailand'), ('TGO', 'Togo'), ('TON', 'Tonga'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('ARE', 'United Arab Emirates'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe')], max_length=200)),
                ('state', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=225)),
                ('is_available', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('slug', models.SlugField(default=book.models.generate_random_number_for_slug, unique=True)),
            ],
        ),
    ]
